"""T21R10 preconstruction gate: synthetic data only, zero runtime rows.

The central rule under test: THE EXACT FROZEN RUNTIME MUST BE ABLE TO LOAD
A SYNTHETIC CORPUS GENERATED BY THE R10 WORLD BUILDER BEFORE BLIND
CONSTRUCTION IS AUTHORIZED, and the exact T21R9 manifest-schema regression
must be refused before any exposure ledger can exist.
"""
from __future__ import annotations

import ast
import copy
import hashlib
import json
import shutil
import sys
import tempfile
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "src"))

import t21r10_freeze_holdout as seal_protocol  # noqa: E402
import t21r10_official_eval as official  # noqa: E402
import t21r10_preconstruction as qualification  # noqa: E402
import t21r10_static_semantics as semantics  # noqa: E402
import t21r10_uniqueness as uniqueness  # noqa: E402
import t21r10_world as world_builder  # noqa: E402
from sciencemath.knowledge.corpus import (  # noqa: E402
    CorruptCorpusError,
    load_corpus,
)


CONTRACT_PATH = (ROOT / "evaluations" / "t21r10" /
                 "preconstruction_contract.json")
SEALED_R9_COMMIT = "4613854abe1e24e86ee818eedc582f79bc1b6559"


def _fixture() -> tuple[list[dict], list[dict], list[dict]]:
    sources, chunks = qualification.build_synthetic_world()
    return sources, chunks, qualification.build_synthetic_suites()


# -- contracts -----------------------------------------------------------

def test_contract_forbids_blind_data_and_runtime_execution() -> None:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    assert contract["blind_data_allowed"] is False
    assert contract["runtime_execution_maximum"] == 0
    assert contract["canonical_parent"] == \
        "273f1984a8d096db546bf543662eaad79f6eff13"
    assert contract["preconstruction_only"] is True
    assert contract["synthetic_fixture"] == {
        "namespace_prefix": "pre10q-",
        "future_blind_reuse_forbidden": True,
        "source_count": 5,
        "chunk_count": 14,
        "world_rows": 19,
        "suite_rows": 8,
    }


def test_contract_preregisters_all_eight_independence_dimensions() -> None:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    assert contract["independence_dimensions"] == list(
        semantics.INDEPENDENCE_DIMENSIONS)
    assert len(contract["independence_dimensions"]) == 8


def test_exactly_32_promotion_floors_unchanged_from_r9() -> None:
    validation = json.loads((ROOT / "evaluations" / "t21r10" /
                             "validation_contract.json").read_text(
        encoding="utf-8"))
    r9_validation = json.loads((ROOT / "evaluations" / "t21r9" /
                                "validation_contract.json").read_text(
        encoding="utf-8"))
    assert validation["promotion_floor_count"] == 32
    assert validation["floors"] == r9_validation["floors"]
    total = sum(len(section) for section in validation["floors"].values())
    assert total == 32
    assert {section: len(floors) for section, floors in
            validation["floors"].items()} == {
        "retrieval": 5, "answers": 5, "citations": 6,
        "abstention_conflict": 5, "temporal": 4, "security": 7,
    }


# -- synthetic fixture ---------------------------------------------------

def test_synthetic_material_uses_only_disposable_namespace() -> None:
    sources, chunks, rows = _fixture()
    assert (len(sources), len(chunks), len(rows)) == (5, 14, 8)
    assert all(source["source_id"].startswith("gk-pre10q-")
               for source in sources)
    assert all("pre10q" in source["source_id"] for source in sources)
    assert all(chunk["chunk_id"].startswith("pre10q-") for chunk in chunks)
    assert all(row["case_id"].startswith("pre10q-") for row in rows)


def test_historical_absent_entity_transformation_removes_stale_metadata() \
        -> None:
    _sources, chunks, rows = _fixture()
    absent = rows[4]
    assert absent["category"] == "injection_absent_entity"
    assert "construction" not in absent
    assert "construction_tags" not in absent
    assert semantics.scan_annotations(rows, chunks)["status"] == "PASS"


def test_equivalent_first_edge_passes_without_nominated_chunk_in_window() \
        -> None:
    sources, chunks, rows = _fixture()
    row = rows[0]
    nominated = row["construction"]["gold_path"]["hop1_edge"]["chunk_id"]
    assert "initial_window_chunk_ids" not in row["construction"]
    result = semantics.audit_path_row(row, sources, chunks)
    assert result["status"] == "PASS"
    assert nominated not in result["derived_initial_window_chunk_ids"]
    assert result["selected_initial_chunk_id"] == \
        "pre10q-chunk-hop1-equivalent"
    assert result["runtime_execution_count"] == 0


def test_all_seven_path_controls_have_expected_outcome() -> None:
    sources, chunks, rows = _fixture()
    controls = qualification.path_achievability_controls(
        sources, chunks, rows[0])
    assert len(controls) == 7
    assert all(control["passed"] for control in controls)
    assert {control["name"] for control in controls} == {
        "nominated_absent_equivalent_edge",
        "actual_window_excludes_all_valid_first_edges",
        "wrong_relation",
        "hand_authored_window_cannot_override_retrieval",
        "wrong_bridge",
        "equal_rank_contradictory_edges",
        "unsafe_nonprojectable_edge",
    }


def test_path_audit_rejects_wrong_source_identity() -> None:
    sources, chunks, rows = _fixture()
    row = copy.deepcopy(rows[0])
    row["construction"]["gold_path"]["hop2_edge"]["source_id"] = \
        "gk-pre10q-src-alpha"
    result = semantics.audit_path_row(row, sources, chunks)
    assert result["status"] == "FAIL"
    assert any("source identity" in defect for defect in result["defects"])


def test_fresh_spoof_fixture_is_structural_only_and_nonresolving() -> None:
    sources, chunks, rows = _fixture()
    result = semantics.audit_spoof_row(rows[1], sources, chunks)
    assert result["status"] == "PASS"
    assert result["locator"] == "r10qz-4e91adbc7032f685"
    assert result["runtime_execution_count"] == 0


def test_all_seven_spoof_controls_have_expected_outcome() -> None:
    sources, chunks, rows = _fixture()
    controls = qualification.spoof_controls(sources, chunks, rows[1])
    assert len(controls) == 7
    assert all(control["passed"] for control in controls)
    assert {control["name"] for control in controls} >= {
        "malformed_provenance",
        "spoof_resolves_real_source",
        "spoof_resolves_real_chunk",
    }


def test_all_sixteen_annotation_controls_have_expected_outcome() -> None:
    _sources, chunks, rows = _fixture()
    controls = qualification.annotation_controls(rows, chunks)
    assert len(controls) == 16
    assert all(control["passed"] for control in controls)
    assert {control["name"] for control in controls} >= {
        "stale_attack_metadata",
        "missing_required_source",
        "corroboration_path_source_overlap",
    }


def test_each_independence_dimension_has_a_negative_control() -> None:
    sources, chunks, rows = _fixture()
    controls = qualification.independence_controls(sources, chunks, rows)
    assert len(controls) == 9
    assert all(control["passed"] for control in controls)
    names = {control["name"] for control in controls}
    assert {f"reused_{dimension}"
            for dimension in semantics.INDEPENDENCE_DIMENSIONS} <= names


def test_static_scanner_uniqueness_and_blindness_all_pass() -> None:
    sources, chunks, rows = _fixture()
    assert qualification.run_static_audit(rows, sources, chunks)["status"] == \
        "PASS"
    assert semantics.scan_annotations(rows, chunks)["status"] == "PASS"
    assert semantics.audit_independence(
        sources, chunks, rows,
        qualification.synthetic_prior_material())["status"] == "UNIQUE"
    assert qualification.run_blindness_audit()["status"] == "PASS"


def test_qualification_sources_have_no_runtime_evaluator_call() -> None:
    forbidden = {"answer_knowledge", "resolve_path", "run_evaluation",
                 "evaluate_holdout", "official_evaluation"}
    for path in (qualification.BUILDER_PATH, qualification.STATIC_AUDIT_PATH):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        called = {
            node.func.id if isinstance(node.func, ast.Name) else node.func.attr
            for node in ast.walk(tree)
            if isinstance(node, ast.Call) and isinstance(
                node.func, (ast.Name, ast.Attribute))
        }
        assert called.isdisjoint(forbidden)


# -- R10 world builder: runtime-compatible manifest (Requirement 1) ------

def _blind_spec() -> dict:
    text = "Spec Entity holds value alpha."
    source_blob = json.dumps({
        "source_id": "gk-spec-source", "source_title": "Spec Source",
        "publisher_or_collection": "spec", "revision_or_version": "v1",
        "text": "",
    }, sort_keys=True, ensure_ascii=False)
    source_hash = hashlib.sha256(source_blob.encode("utf-8")).hexdigest()
    return {
        "world": [{"entity_id": "gk-spec-entity", "name": "Spec Entity"}],
        "sources": [{
            "source_id": "gk-spec-source", "source_title": "Spec Source",
            "source_type": "reference", "source_uri_or_origin": "spec://",
            "publisher_or_collection": "spec", "license": "CC0-1.0",
            "revision_or_version": "v1",
            "retrieved_at_or_snapshot_date": "2026-01-01",
            "language": "en", "authority_class": "PRIMARY_REFERENCE",
            "freshness_class": "STATIC", "topic_tags": ["spec"],
            "content_hash": source_hash, "document_hash": source_hash,
        }],
        "chunks": [{
            "chunk_id": "gk-spec-source:spec:0", "source_id": "gk-spec-source",
            "section": "spec", "text": text,
            "ordinal": 0, "span": [0, len(text)],
            "metadata": {"fact_entity": "Spec Entity",
                         "fact_attribute": "holds", "fact_value": "alpha"},
            "content_hash": hashlib.sha256(text.encode("utf-8")).hexdigest(),
        }],
    }


def test_r10_world_manifest_is_load_corpus_compatible() -> None:
    """Requirement 1 + 2: the world builder's manifest loads under the
    ACTUAL frozen runtime, and counts agree."""
    spec = _blind_spec()
    with tempfile.TemporaryDirectory(prefix="t21r10-world-load-") as tmp:
        output = Path(tmp) / "world"
        manifest = world_builder.materialize_world(spec, output)
        corpus = load_corpus(output)
        assert manifest["source_count"] == len(corpus.sources) == 1
        assert manifest["chunk_count"] == len(corpus.chunks) == 1
        for key in ("corpus_version", "snapshot_date", "source_count",
                    "chunk_count", "domains", "license_summary",
                    "file_checksums", "manifest_checksum"):
            assert key in manifest, key
        assert set(manifest["file_checksums"]) == {"sources.jsonl",
                                                   "chunks.jsonl"}


def test_r10_world_manifest_checksums_match_runtime_lf_policy() -> None:
    spec = _blind_spec()
    with tempfile.TemporaryDirectory(prefix="t21r10-world-sha-") as tmp:
        output = Path(tmp) / "world"
        manifest = world_builder.materialize_world(spec, output)
        for name, expected in manifest["file_checksums"].items():
            data = (output / name).read_bytes().replace(b"\r\n", b"\n")
            assert hashlib.sha256(data).hexdigest() == expected
        blob = json.dumps({key: value for key, value in manifest.items()
                           if key != "manifest_checksum"},
                          sort_keys=True, ensure_ascii=False)
        assert hashlib.sha256(blob.encode("utf-8")).hexdigest() == \
            manifest["manifest_checksum"]


def test_r10_world_builder_refuses_incomplete_runtime_records() -> None:
    spec = _blind_spec()
    del spec["sources"][0]["license"]
    with tempfile.TemporaryDirectory(prefix="t21r10-world-neg-") as tmp:
        with pytest.raises(ValueError, match="runtime fields"):
            world_builder.materialize_world(spec, Path(tmp) / "world")


def test_r10_world_builder_refuses_dangling_chunk_source() -> None:
    spec = _blind_spec()
    spec["chunks"][0]["source_id"] = "gk-spec-other-source"
    with tempfile.TemporaryDirectory(prefix="t21r10-world-neg-") as tmp:
        with pytest.raises(ValueError):
            world_builder.materialize_world(spec, Path(tmp) / "world")


def test_r10_world_builder_refuses_disposable_prefix_in_blind_data() -> None:
    spec = _blind_spec()
    spec["sources"][0]["source_id"] = "gk-pre10q-src-blind"
    with tempfile.TemporaryDirectory(prefix="t21r10-world-neg-") as tmp:
        with pytest.raises(ValueError):
            world_builder.materialize_world(spec, Path(tmp) / "world")


# -- actual load_corpus compatibility gate (Requirement 2) ---------------

def test_actual_load_succeeds_and_agrees_with_manifest_counts() -> None:
    sources, chunks, _rows = _fixture()
    with tempfile.TemporaryDirectory(prefix="t21r10-loadgate-") as tmp:
        corpus_dir = Path(tmp) / "corpus"
        qualification.write_runtime_compatible_corpus(
            corpus_dir, sources, chunks)
        gate = qualification.corpus_load_gate(corpus_dir)
        assert gate["status"] == "PASS", gate["defects"]
        assert gate["sources_loaded"] == gate["manifest_source_count"] == 5
        assert gate["chunks_loaded"] == gate["manifest_chunk_count"] == 14
        assert gate["runtime_rows_executed"] == 0


def test_actual_load_executes_zero_holdout_rows_and_writes_nothing() -> None:
    sources, chunks, _rows = _fixture()
    with tempfile.TemporaryDirectory(prefix="t21r10-loadgate-") as tmp:
        corpus_dir = Path(tmp) / "corpus"
        qualification.write_runtime_compatible_corpus(
            corpus_dir, sources, chunks)
        before = sorted(path.name for path in corpus_dir.iterdir())
        gate = qualification.corpus_load_gate(corpus_dir)
        assert gate["status"] == "PASS"
        assert gate["runtime_rows_executed"] == 0
        after = sorted(path.name for path in corpus_dir.iterdir())
        assert before == after  # the compatibility load writes nothing


# -- negative load controls (Requirement 2) ------------------------------

def test_negative_load_controls_all_fail_closed() -> None:
    sources, chunks, _rows = _fixture()
    report = qualification.negative_load_controls(sources, chunks)
    assert report["status"] == "PASS", [
        control for control in report["controls"] if not control["passed"]]
    assert report["passed"] == report["total"]
    names = {control["name"] for control in report["controls"]}
    assert names >= {
        "missing_source_count", "wrong_source_count",
        "missing_chunk_count", "wrong_chunk_count",
        "missing_file_checksums", "wrong_sources_checksum",
        "wrong_chunks_checksum", "missing_sources_file",
        "missing_chunks_file", "malformed_source_record",
        "malformed_chunk_record", "chunk_content_hash_corruption",
        "chunk_source_referential_integrity",
    }
    runtime_controls = [control for control in report["controls"]
                        if control["layer"] == "runtime_load"]
    assert len(runtime_controls) == 13
    assert all(control["refused"] for control in runtime_controls)


def test_source_count_mismatch_fails_load_corpus() -> None:
    sources, chunks, _rows = _fixture()
    with tempfile.TemporaryDirectory(prefix="t21r10-negcount-") as tmp:
        corpus_dir = Path(tmp) / "corpus"
        qualification.write_runtime_compatible_corpus(
            corpus_dir, sources, chunks)
        manifest = json.loads((corpus_dir / "corpus_manifest.json").read_text(
            encoding="utf-8"))
        manifest["source_count"] = 999
        (corpus_dir / "corpus_manifest.json").write_text(json.dumps(manifest))
        with pytest.raises(CorruptCorpusError):
            load_corpus(corpus_dir)


def test_chunk_count_mismatch_fails_load_corpus() -> None:
    sources, chunks, _rows = _fixture()
    with tempfile.TemporaryDirectory(prefix="t21r10-negcount-") as tmp:
        corpus_dir = Path(tmp) / "corpus"
        qualification.write_runtime_compatible_corpus(
            corpus_dir, sources, chunks)
        manifest = json.loads((corpus_dir / "corpus_manifest.json").read_text(
            encoding="utf-8"))
        manifest["chunk_count"] = 999
        (corpus_dir / "corpus_manifest.json").write_text(json.dumps(manifest))
        with pytest.raises(CorruptCorpusError):
            load_corpus(corpus_dir)


def test_source_and_chunk_checksum_mismatches_fail_load_corpus() -> None:
    sources, chunks, _rows = _fixture()
    for name in ("sources.jsonl", "chunks.jsonl"):
        with tempfile.TemporaryDirectory(prefix="t21r10-negsha-") as tmp:
            corpus_dir = Path(tmp) / "corpus"
            qualification.write_runtime_compatible_corpus(
                corpus_dir, sources, chunks)
            manifest = json.loads(
                (corpus_dir / "corpus_manifest.json").read_text(
                    encoding="utf-8"))
            manifest["file_checksums"][name] = "0" * 64
            (corpus_dir / "corpus_manifest.json").write_text(
                json.dumps(manifest))
            with pytest.raises(CorruptCorpusError):
                load_corpus(corpus_dir)


# -- official preflight loadability + R9 regression (Requirement 3/4) ----

def _sealed_candidate(tmp: str) -> tuple[Path, Path]:
    sources, chunks, rows = _fixture()
    root = Path(tmp) / "synthetic_repository"
    qualification.materialize_real_protocol_candidate(root, sources, chunks,
                                                      rows)
    seal_protocol.seal(root)
    return root, root / "evaluations" / "t21r10"


def test_preflight_loads_corpus_before_any_ledger_can_exist() -> None:
    with tempfile.TemporaryDirectory(prefix="t21r10-preflight-") as tmp:
        root, out_dir = _sealed_candidate(tmp)
        report = official.preflight(root)
        assert report["status"] == "PASS", report["defects"]
        assert report["corpus_compatibility"]["status"] == "PASS"
        assert report["corpus_compatibility"]["source_count"] == 5
        assert report["corpus_compatibility"]["chunk_count"] == 14
        assert report["corpus_compatibility"][
            "runtime_evaluation_rows"] == 0
        assert report["runtime_execution_count"] == 0
        assert report["ledger_written"] is False
        # preflight is strictly pre-ledger: no exposure artifact may exist
        assert not (out_dir / "evaluation_run_ledger.json").exists()
        assert not (out_dir / "raw_results.jsonl").exists()
        assert not (out_dir / "holdout_results.json").exists()


def test_r9_manifest_schema_regression() -> None:
    """The exact T21R9 failure: an R9 construction-schema manifest
    (counts/files_sha256 without runtime keys) must fail the official
    preflight before any ledger exists, with zero holdout rows."""
    with tempfile.TemporaryDirectory(prefix="t21r10-r9reg-") as tmp:
        root, out_dir = _sealed_candidate(tmp)
        corpus_dir = root / "rag" / "gk_holdout_t21r10"
        manifest = json.loads((corpus_dir / "corpus_manifest.json").read_text(
            encoding="utf-8"))
        legacy_r9 = {
            "artifact": "T21R10_BLIND_CORPUS_MANIFEST",
            "counts": {"sources": manifest["source_count"],
                       "chunks": manifest["chunk_count"]},
            "files_sha256": dict(manifest["file_checksums"]),
            "runtime_rows_executed": 0,
        }
        (corpus_dir / "corpus_manifest.json").write_text(json.dumps(legacy_r9))
        report = official.preflight(root)
        assert report["status"] == "FAIL"
        assert any("corpus compatibility" in defect
                   for defect in report["defects"])
        assert report["ledger_written"] is False
        assert report["runtime_execution_count"] == 0
        assert not (out_dir / "evaluation_run_ledger.json").exists()
        assert not (out_dir / "raw_results.jsonl").exists()
        assert not (out_dir / "holdout_results.json").exists()


def test_one_shot_ledger_still_refuses_rerun_after_preflight() -> None:
    with tempfile.TemporaryDirectory(prefix="t21r10-oneshot-") as tmp:
        root, out_dir = _sealed_candidate(tmp)
        paths = official.build_paths(root)
        official._write_ledger(paths, "started")
        # A rerun is refused at preflight (exposure-artifact absence is
        # checked first), so no second ledger write and no row can happen.
        with pytest.raises(SystemExit, match="one-shot exposure artifact "
                                             "exists"):
            official.execute(paths)
        ledger = json.loads((out_dir /
                             "evaluation_run_ledger.json").read_text(
            encoding="utf-8"))
        assert ledger["phase"] == "started"
        assert ledger["official_runtime_exposures"] == 1
        assert not (out_dir / "raw_results.jsonl").exists()
        assert not (out_dir / "holdout_results.json").exists()


# -- prior exclusion (Requirement 5) -------------------------------------

def test_prior_exclusion_covers_t21_through_t21r9_sealed() -> None:
    artifact = json.loads((ROOT / "evaluations" / "t21r10" /
                           "prior_exclusion_fingerprints.json").read_text(
        encoding="utf-8"))
    assert set(artifact["milestones"]) == {
        "T21", "T21R", "T21R2", "T21R3", "T21R4", "T21R5", "T21R6",
        "T21R7", "T21R8_DIAGNOSTIC", "T21R9_SEALED"}
    decoded = uniqueness.validate_artifact(artifact)
    assert len(decoded) == 10
    for milestone, dimensions in decoded.items():
        assert set(dimensions) == set(uniqueness.DIMENSIONS)
        assert len(dimensions) == 8
        for _dimension, values in dimensions.items():
            assert isinstance(values, set)


def test_r9_fingerprint_reuse_is_detected() -> None:
    artifact = json.loads((ROOT / "evaluations" / "t21r10" /
                           "prior_exclusion_fingerprints.json").read_text(
        encoding="utf-8"))
    decoded = uniqueness.validate_artifact(artifact)
    poisoned = {dimension: set() for dimension in uniqueness.DIMENSIONS}
    poisoned["case_ids"].add(next(iter(
        decoded["T21R9_SEALED"]["case_ids"])))
    poisoned["chunk_ids"].add(next(iter(
        decoded["T21R9_SEALED"]["chunk_ids"])))
    report = uniqueness.audit_fingerprint_sets(poisoned, artifact)
    assert report["status"] == "OVERLAP"
    assert report["overlap_total"] == 2
    assert report["overlap_counts"]["T21R9_SEALED"]["case_ids"] == 1
    assert report["overlap_counts"]["T21R9_SEALED"]["chunk_ids"] == 1


def test_committed_exclusion_artifact_contains_no_raw_r9_material() -> None:
    artifact = json.loads((ROOT / "evaluations" / "t21r10" /
                           "prior_exclusion_fingerprints.json").read_text(
        encoding="utf-8"))
    assert artifact["raw_values_included"] is False
    assert artifact["fingerprint_algorithm"] == "SHA-256"
    decoded = uniqueness.validate_artifact(artifact)
    for milestone, dimensions in decoded.items():
        for _dimension, values in dimensions.items():
            for value in values:
                assert len(value) == 64
                assert all(char in "0123456789abcdef" for char in value)
    sealed = artifact["milestones"]["T21R9_SEALED"]
    assert sealed["raw_material_committed"] is False
    assert sealed["sealed_commit"] == SEALED_R9_COMMIT


# -- frozen component drift (Requirements preserved from R9) -------------

def test_frozen_runtime_and_evaluator_drift_refuse_seal_and_preflight() \
        -> None:
    with tempfile.TemporaryDirectory(prefix="t21r10-drift-") as tmp:
        root, _out_dir = _sealed_candidate(tmp)
        controls = qualification.real_protocol_seal_controls(root)
        names = {control["name"]: control["passed"] for control in controls}
        assert names["runtime_component_hash_drift"] is True
        assert names["evaluator_component_hash_drift"] is True
        assert names["freeze_file_component_map_tamper"] is True
        assert len(controls) == 12
        assert all(control["passed"] for control in controls)


# -- end-to-end qualification -------------------------------------------

def test_end_to_end_nonblind_miniature_and_all_controls_pass() -> None:
    report = qualification.run_qualification(write_report=False)
    assert report["status"] == "PASS", json.dumps(report, indent=1)[:2000]
    assert report["counts"] == {
        "sources": 5, "chunks": 14, "world_rows": 19, "suite_rows": 8}
    assert all(status == "PASS" for status in report["stages"].values())
    assert report["stages"]["corpus_compatibility_load"] == "PASS"
    assert report["runtime_rows_executed"] == 0
    assert report["controls"]["seal_preflight"]["passed"] == 12
    assert report["controls"]["negative_load"]["passed"] == \
        report["controls"]["negative_load"]["total"] == 14
    regression = report["controls"]["r9_manifest_schema_regression"]
    assert regression["controls"][0]["name"] == "r9_manifest_schema_regression"
    assert regression["controls"][0]["passed"] is True
    assert regression["controls"][0]["ledger_written"] is False
    assert regression["controls"][0]["runtime_evaluation_rows"] == 0


def test_every_real_r10_holdout_and_exposure_path_remains_absent() -> None:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    assert qualification.prohibited_real_paths() == []
    assert len(contract["prohibited_real_r10_paths"]) == 7
    for relative in contract["prohibited_real_r10_paths"]:
        assert not (ROOT / relative).exists()