"""T16.6 — source trust classes.

Class is NOT proof of correctness. It influences ranking/confidence only.
Low-trust sources may still be relevant. High-trust sources are not
infallible.
"""
from __future__ import annotations

OFFICIAL_PRIMARY = "OFFICIAL_PRIMARY"
PRIMARY_DATA = "PRIMARY_DATA"
PEER_REVIEWED = "PEER_REVIEWED"
GOVERNMENT = "GOVERNMENT"
STANDARDS_BODY = "STANDARDS_BODY"
FIRST_PARTY_TECHNICAL = "FIRST_PARTY_TECHNICAL"
REPUTABLE_SECONDARY = "REPUTABLE_SECONDARY"
SPECIALIST_SECONDARY = "SPECIALIST_SECONDARY"
USER_GENERATED = "USER_GENERATED"
SOCIAL_MEDIA = "SOCIAL_MEDIA"
AGGREGATOR = "AGGREGATOR"
UNKNOWN = "UNKNOWN"
LOW_TRUST = "LOW_TRUST"

TRUST_CLASSES = (
    OFFICIAL_PRIMARY, PRIMARY_DATA, PEER_REVIEWED, GOVERNMENT,
    STANDARDS_BODY, FIRST_PARTY_TECHNICAL, REPUTABLE_SECONDARY,
    SPECIALIST_SECONDARY, USER_GENERATED, SOCIAL_MEDIA, AGGREGATOR,
    UNKNOWN, LOW_TRUST,
)

# Ranking influence only. Never used as a correctness proof.
TRUST_WEIGHT = {
    OFFICIAL_PRIMARY: 1.00,
    PRIMARY_DATA: 0.96,
    PEER_REVIEWED: 0.94,
    GOVERNMENT: 0.93,
    STANDARDS_BODY: 0.93,
    FIRST_PARTY_TECHNICAL: 0.90,
    REPUTABLE_SECONDARY: 0.72,
    SPECIALIST_SECONDARY: 0.64,
    USER_GENERATED: 0.40,
    SOCIAL_MEDIA: 0.28,
    AGGREGATOR: 0.35,
    UNKNOWN: 0.30,
    LOW_TRUST: 0.12,
}

PRIMARY_CLASSES = {
    OFFICIAL_PRIMARY, PRIMARY_DATA, PEER_REVIEWED, GOVERNMENT,
    STANDARDS_BODY, FIRST_PARTY_TECHNICAL,
}


def is_primary(trust_class: str) -> bool:
    return trust_class in PRIMARY_CLASSES


def weight(trust_class: str) -> float:
    return TRUST_WEIGHT.get(trust_class, TRUST_WEIGHT[UNKNOWN])
