"""T19.2 typed planning operations. No operation performs side effects."""
from __future__ import annotations

PLAN_CREATE = "PLAN_CREATE"
PLAN_VALIDATE = "PLAN_VALIDATE"
PLAN_DECOMPOSE = "PLAN_DECOMPOSE"
PLAN_SEQUENCE = "PLAN_SEQUENCE"
PLAN_ADD_DEPENDENCY = "PLAN_ADD_DEPENDENCY"
PLAN_CHECKPOINT = "PLAN_CHECKPOINT"
PLAN_OBSERVE = "PLAN_OBSERVE"
PLAN_REPLAN = "PLAN_REPLAN"
PLAN_RECOVER = "PLAN_RECOVER"
PLAN_BLOCK = "PLAN_BLOCK"
PLAN_RESUME = "PLAN_RESUME"
PLAN_COMPLETE = "PLAN_COMPLETE"
PLAN_ABORT = "PLAN_ABORT"
PLAN_NEEDS_CLARIFICATION = "PLAN_NEEDS_CLARIFICATION"
PLAN_INSUFFICIENT_CAPABILITY = "PLAN_INSUFFICIENT_CAPABILITY"
PLAN_BUDGET_EXCEEDED = "PLAN_BUDGET_EXCEEDED"
PLAN_POLICY_BLOCKED = "PLAN_POLICY_BLOCKED"

PLAN_OPS = (
    PLAN_CREATE, PLAN_VALIDATE, PLAN_DECOMPOSE, PLAN_SEQUENCE,
    PLAN_ADD_DEPENDENCY, PLAN_CHECKPOINT, PLAN_OBSERVE, PLAN_REPLAN,
    PLAN_RECOVER, PLAN_BLOCK, PLAN_RESUME, PLAN_COMPLETE, PLAN_ABORT,
    PLAN_NEEDS_CLARIFICATION, PLAN_INSUFFICIENT_CAPABILITY,
    PLAN_BUDGET_EXCEEDED, PLAN_POLICY_BLOCKED,
)

PLAN_STATUSES = (
    "DRAFT", "VALIDATED", "READY", "IN_PROGRESS", "BLOCKED",
    "NEEDS_REPLAN", "COMPLETE", "ABORTED", "FAILED",
)

TASK_STATUSES = (
    "PENDING", "READY", "RUNNING_SIMULATED", "SUCCEEDED", "FAILED",
    "BLOCKED", "SKIPPED", "INVALIDATED",
)

SIDE_EFFECT_CLASSES = (
    "NONE", "READ_ONLY", "LOCAL_REVERSIBLE", "LOCAL_MUTATION",
    "NETWORK_READ", "NETWORK_MUTATION", "EXTERNAL_IRREVERSIBLE", "PAID",
)

FAILURE_CLASSES = (
    "TRANSIENT", "PERMANENT", "POLICY_BLOCK", "MISSING_INPUT",
    "INVALID_ASSUMPTION", "CAPABILITY_UNAVAILABLE", "BUDGET_EXCEEDED",
    "UNKNOWN",
)

ASSUMPTION_STATUSES = (
    "UNVERIFIED", "VERIFIED", "INVALIDATED", "SUPERSEDED",
)

KNOWN_TASK_SKILLS = (
    "SCICOMP", "CODE", "WEB_RESEARCH", "DOCUMENT", "MEMORY",
    "MATH_T4", "SCIENCE_RAG", "GENERAL",
)

COST_FREE = "FREE"
COST_PAID = "PAID"

AUTHORITY_PROPOSE_ONLY = "PROPOSE_ONLY"

SCHEMA_VERSION = 1
PAID_COMPUTE_GATE_REQUIRED = "PAID_COMPUTE_GATE_REQUIRED"
