"""T32 Phase 4: machine-generated, programmatically verified math drills.

Every drill is generated by computing the answer chain FORWARD from seeded
parameters (seed 42), rendering explicit step lines; every rendered
arithmetic equality is then RE-verified independently by re-evaluating each
side, the boxed final must equal the computed final, and any drill whose
re-verification fails is dropped. Deterministic: the same file every run.

Targets follow the canonical T30 math contract (``Final answer: \\boxed{}``)
through ``math_response`` and sit inside the 1600-char math budget.

Diagnostic targeting (Phase 1 taxonomy): the adapter's measured failure modes
are plain-arithmetic slips (~17% of adapter-wrong math rows) and
reasoning-chain / underderivation errors (~77%). The drill families therefore
emphasize explicit calculation chains over single-step recall.
"""
from __future__ import annotations

import hashlib
import json
import math
import random
import sys
from fractions import Fraction
from pathlib import Path

sys.path.insert(0, "scripts")
sys.path.insert(0, "src")

from common import REPO_ROOT  # noqa: E402

from sciencemath.datasets.normalize import text_fingerprint  # noqa: E402
from sciencemath.datasets.schema import make_id  # noqa: E402
from sciencemath.training.sft_format import math_response  # noqa: E402

ROOT = REPO_ROOT
OUT = ROOT / "training/t32/drills"
TOTAL = 400


# ---------------------------------------------------------------- verify


def _num(s: str):
    try:
        return float(s.replace(",", ""))
    except ValueError:
        return None


def _tolerant(v: float, c: float) -> bool:
    return abs(v - c) <= max(0.005 * max(1.0, abs(v)), 0.005)


def _plain_arith(seg: str) -> bool:
    return bool(seg.strip()) and seg != seg.strip("\\") and all(
        ch in "0123456789.+-*/() " for ch in seg)


def verify_lines(lines: list[str]) -> list[str]:
    """Independent re-verification of rendered equality chains.

    A line ``a op b = c = d`` is split on '='; each consecutive pair of
    segments must agree numerically when BOTH are pure arithmetic. Prose
    segments (letters, LCD(), P(x), words) are skipped. Returns violation
    strings (empty list = verified). The boxed final is checked separately
    against the composed target."""
    bad: list[str] = []
    for line in lines:
        segs = [s.strip() for s in line.split("=")]
        if len(segs) < 2:
            continue
        vals = [_num(s) for s in segs]
        for a, b in zip(vals, vals[1:]):
            if a is None or b is None:
                continue          # prose or symbolic segment; not a step check
            if not _tolerant(a, b):
                bad.append(line)
                break
    return bad


def fm(x: float) -> str:
    """Format a value compactly (int when integral, else short decimal)."""
    if abs(x - round(x)) < 1e-9:
        n = int(round(x))
        return f"{n:,}" if abs(n) >= 10000 else str(n)
    return f"{x.rstrip('0').rstrip('.') if isinstance(x, str) else x:g}"


def g(x) -> str:
    return f"{x:g}" if isinstance(x, float) else str(x)


# ------------------------------------------------------------- families


def fam_chain(rng, k):
    """3-term addition/subtraction chain, expanded step by step."""
    a, b, c = (rng.randint(15, 900) for _ in range(3))
    op1, op2 = rng.choice("+-"), rng.choice("+-")
    m1 = a + b if op1 == "+" else a - b
    final = m1 + c if op2 == "+" else m1 - c
    q = f"Calculate {a} {op1} {b} {op2} {c} left to right."
    sol = [f"{a} {op1} {b} = {fm(m1)}", f"{fm(m1)} {op2} {c} = {fm(final)}"]
    return q, sol, fm(final)


def fam_multichain(rng, k):
    """Two-step product chain: (a x b) +- c, explicit partial product."""
    a, b, c = rng.randint(12, 499), rng.randint(2, 60), rng.randint(10, 900)
    op = rng.choice("+-")
    p = a * b
    final = p + c if op == "+" else p - c
    q = f"Compute {a} × {b} {'+' if op == '+' else '-'} {c}."
    sol = [f"{a} × {b} = {fm(p)}",
           f"{fm(p)} {'+' if op == '+' else '-'} {c} = {fm(final)}"]
    return q, sol, fm(final)


def fam_percent_of(rng, k):
    p = rng.choice([5, 10, 15, 20, 25, 30, 40, 50, 60, 75, 80, 90])
    n = rng.randint(20, 800)
    v = n * p / 100
    q = f"What is {p}% of {n}?"
    sol = [f"{p}% of {n} = {n} × {p}/100 = {n} × {fm(p / 100)} = {fm(v)}"]
    return q, sol, fm(v)


def fam_percent_change(rng, k):
    p = rng.choice([5, 10, 15, 20, 25, 50])
    n = rng.choice([40, 80, 120, 200, 240, 300, 400, 500, 600])
    up = rng.random() < 0.5
    d = fm(n * p / 100)
    v = n * (1 + p / 100) if up else n * (1 - p / 100)
    q = (f"A quantity is {n} and {'increases' if up else 'decreases'} by "
         f"{p}%. What is its new value?")
    sol = [f"Change = {n} × {p}/100 = {d}",
           f"{n} {'+' if up else '-'} {d} = {fm(v)}"]
    return q, sol, fm(v)


def fam_frac_add(rng, k):
    def pick():
        d = rng.choice([2, 3, 4, 5, 6, 8, 10, 12])
        return Fraction(rng.randint(1, d - 1), d)
    f1, f2 = pick(), pick()
    sub = rng.random() < 0.4
    val = f1 - f2 if sub else f1 + f2
    if val <= 0 or val.denominator > 24:
        return None
    op = "-" if sub else "+"
    d1, d2 = f1.denominator, f2.denominator
    lcd = d1 * d2 // math.gcd(d1, d2)
    a, b = f1.numerator * (lcd // d1), f2.numerator * (lcd // d2)
    q = (f"Calculate {f1.numerator}/{d1} {op} {f2.numerator}/{d2} "
         f"(lowest terms).")
    sol = [f"LCD({d1}, {d2}) = {lcd}",
           f"{f1} = {a}/{lcd}, {f2} = {b}/{lcd}",
           f"{a}/{lcd} {'-' if sub else '+'} {b}/{lcd} = "
           f"{val.numerator}/{val.denominator}"]
    return q, sol, f"{val.numerator}/{val.denominator}"


def fam_frac_mul(rng, k):
    d1 = rng.choice([2, 3, 4, 5, 6])
    f1 = Fraction(rng.randint(1, d1 - 1), d1)
    d2 = rng.choice([2, 3, 4, 5, 6, 7, 8])
    f2 = Fraction(rng.randint(1, d2 - 1), d2)
    val = f1 * f2
    q = f"Calculate {f1} × {f2} (lowest terms)."
    sol = [f"{f1} × {f2} = {f1.numerator * f2.numerator}/"
           f"{d1 * d2} = {val.numerator}/{val.denominator}"]
    return q, sol, f"{val.numerator}/{val.denominator}"


def fam_ratio_share(rng, k):
    x, y = rng.randint(1, 5), rng.randint(1, 5)
    if x == y:
        y += 1
    total = (x + y) * rng.randint(6, 60)
    unit = total // (x + y)
    a, b = unit * x, unit * y
    q = f"Divide {total} in the ratio {x}:{y}. What is the larger share?"
    sol = [f"Total parts = {x} + {y} = {x + y}",
           f"One part = {total} / {x + y} = {unit}",
           f"Shares = {x} × {unit} = {fm(a)} and {y} × {unit} = {fm(b)}"]
    return q, sol, fm(max(a, b))


def fam_linear_eq(rng, k):
    a, x = rng.randint(2, 9), rng.randint(0, 40)
    b = rng.randint(-40, 40)
    c = a * x + b
    q = f"Solve for x: {a}x {'+' if b >= 0 else '-'} {abs(b)} = {c}."
    sol = [f"{a}x = {c} {'-' if b >= 0 else '+'} {abs(b)} = {c - b}",
           f"x = {c - b}/{a} = {fm(x)}"]
    return q, sol, fm(x)


def fam_mean(rng, k):
    nums = [rng.randint(1, 100) for _ in range(4)]
    m = rng.randint(1, 100)
    x = m * 5 - sum(nums)
    if x < 1:
        return None
    q = (f"The mean of five numbers {nums[0]}, {nums[1]}, {nums[2]}, "
         f"{nums[3]}, and x is {m}. What is x?")
    tot = m * 5
    known = sum(nums)
    sol = [f"Required sum = mean × count = {m} × 5 = {tot}",
           f"Known sum = {' + '.join(str(n) for n in nums)} = {known}",
           f"x = {tot} - {known} = {x}"]
    return q, sol, str(x)


def fam_word_discount(rng, k):
    price = rng.choice([120, 240, 350, 480, 640, 750, 899, 1250])
    p = rng.choice([10, 15, 20, 25, 30])
    tax = rng.choice([0, 5, 8, 10])
    cut = price * p / 100
    after = price - cut
    final = after * (1 + tax / 100)
    q = (f"A jacket costs ${price}. It is discounted by {p}%, then sales tax "
         f"of {tax}% is added to the discounted price. What is the final "
         f"price in dollars?")
    sol = [f"Discount = {price} × {p}/100 = {fm(cut)}",
           f"Discounted price = {price} - {fm(cut)} = {fm(after)}",
           f"Tax = {fm(after)} × {tax}/100 = {fm(after * tax / 100)}",
           f"Final price = {fm(after)} + {fm(after * tax / 100)} = {fm(final)}"]
    return q, sol, fm(final)


def fam_rate(rng, k):
    s = rng.choice([30, 40, 45, 50, 55, 60, 65, 70, 80])
    t = rng.randint(2, 12)
    d = s * t
    q = f"A car travels at {s} km/h for {t} hours. How far does it travel?"
    sol = [f"Distance = speed × time = {s} × {t} = {fm(d)}"]
    return q, sol, fm(d)


def fam_inverse_percent(rng, k):
    p = rng.choice([10, 20, 25, 40, 50, 75])
    base = rng.choice([40, 60, 80, 120, 160, 200, 320])
    v = base * p / 100
    q = f"{fm(v)} is {p}% of what number?"
    sol = [f"n × {p}/100 = {fm(v)}",
           f"n = {fm(v)} × 100/{p} = {fm(v * 100 / p)}"]
    return q, sol, fm(v * 100 / p)


def _pf(n: int) -> list[str]:
    out, d = [], 2
    v = n
    while d * d <= v:
        while v % d == 0:
            out.append(str(d))
            v //= d
        d += 1
    if v > 1:
        out.append(str(v))
    return out


def fam_gcd_lcm(rng, k):
    a, b = rng.randint(12, 96), rng.randint(12, 96)
    gg = math.gcd(a, b)
    lcm = a * b // gg
    want_gcd = rng.random() < 0.5
    if want_gcd:
        q = f"Find the greatest common divisor of {a} and {b}."
        sol = [f"Prime factors: {a} = {' × '.join(_pf(a))}",
               f"Prime factors: {b} = {' × '.join(_pf(b))}",
               f"GCD = product of the common prime factors = {gg}"]
        return q, sol, str(gg)
    q = f"Find the least common multiple of {a} and {b}."
    sol = [f"Prime factors: {a} = {' × '.join(_pf(a))}",
           f"Prime factors: {b} = {' × '.join(_pf(b))}",
           f"LCM = {a} × {b} / {gg} = {fm(lcm)}"]
    return q, sol, fm(lcm)


def fam_perm(rng, k):
    n = rng.randint(4, 7)
    r = rng.randint(2, min(4, n - 1))
    v = 1
    factors = " × ".join(str(t) for t in range(n, n - r, -1))
    q = f"How many ways can {r} distinct items be arranged, chosen from {n}?"
    if r == 1:
        sol = [f"Arrangements = {n}"]
        v = n
    else:
        v = math.perm(n, r)
        sol = [f"Arrangements = {n} × {n-1}{' × ' + str(n-2) if r >= 3 else ''}"
               f"{' × ' + str(n-3) if r >= 4 else ''} = {v}"]
    return q, sol, str(v)


def fam_prob(rng, k):
    succ = rng.randint(1, 5)
    tot = rng.choice([6, 8, 10, 12, 20])
    if succ >= tot:
        return None
    val = Fraction(succ, tot)
    q = (f"A spinner has {tot} equal sectors and {succ} of them are red. "
         f"What is the probability of landing on red (lowest terms)?")
    sol = [f"P(red) = favourable / total = {succ}/{tot} = "
           f"{val.numerator}/{val.denominator}"]
    return q, sol, f"{val.numerator}/{val.denominator}"


def fam_geometry(rng, k):
    kind = rng.choice(["rect", "tri", "box"])
    if kind == "rect":
        w, h = rng.randint(3, 25), rng.randint(3, 25)
        q = f"A rectangle has width {w} cm and height {h} cm. What is its area in square centimeters?"
        sol = [f"Area = width × height = {w} × {h} = {fm(w * h)}"]
        return q, sol, fm(w * h)
    if kind == "tri":
        b = rng.choice([6, 8, 10, 12, 14, 16])
        h = rng.randint(3, 20)
        if (b * h) % 2:
            h += 1
        if (b * h) % 2:
            return None
        a = b * h // 2
        q = f"A triangle has base {b} cm and height {h} cm. What is its area in square centimeters?"
        sol = [f"Area = base × height / 2 = {b} × {h} / 2 = {b * h} / 2 = {fm(a)}"]
        return q, sol, fm(a)
    w, d, h = (rng.randint(2, 12) for _ in range(3))
    q = f"A box has dimensions {w} cm × {d} cm × {h} cm. What is its volume in cubic centimeters?"
    sol = [f"Volume = {w} × {d} × {h} = {fm(w * d)} × {h} = {fm(w * d * h)}"]
    return q, sol, fm(w * d * h)


def fam_decimal(rng, k):
    a, b = rng.randint(100, 9900) / 100, rng.randint(100, 5000) / 100
    op = rng.choice("+-")
    v = a + b if op == "+" else a - b
    if abs(v) < 1:
        return None
    q = f"Calculate {a:.2f} {op} {b:.2f}."
    sol = [f"{a:.2f} {op} {b:.2f} = {v:.2f}"]
    return q, sol, f"{v:.2f}"


def fam_frac_dec(rng, k):
    d = rng.choice([2, 4, 5, 8, 10, 16, 20, 25])
    f = Fraction(rng.randint(1, d - 1), d)
    if f.denominator != d:
        return None
    dec = f.numerator / d
    q = f"Write {f.numerator}/{d} as a decimal."
    sol = [f"{f.numerator}/{d} = {f.numerator} ÷ {d} = {dec:g}"]
    return q, sol, f"{dec:g}"


def fam_word_multi(rng, k):
    """A 4-step chain word problem (premature-answer / underderivation target)."""
    n0 = rng.randint(40, 240)
    if n0 % 4:
        n0 += 4 - n0 % 4
    sold = n0 // 4
    extra = rng.randint(15, 90)
    bags = rng.randint(10, 30)
    left = (n0 - sold + extra) % bags
    q = (f"A market has {n0} apples, sells exactly a quarter of them, then "
         f"receives {extra} more. All apples are packed into bags of {bags}. "
         f"How many apples are left over after packing?")
    kept = n0 - sold
    tot = kept + extra
    sol = [f"Sold = {n0} / 4 = {sold}",
           f"Kept = {n0} - {sold} = {kept}",
           f"After receiving: {kept} + {extra} = {tot}",
           f"Left over = {tot} mod {bags} = {left}"]
    return q, sol, str(left)


def fam_unit_conv(rng, k):
    m = rng.choice([2.5, 3.2, 4.75, 6.5, 8.1, 9.9])
    v = m * 100
    q = f"How many centimeters are {m} meters?"
    sol = [f"{m} m = {m} × 100 cm = {g(v)} cm"]
    return q, sol, g(v)


def fam_square_root(rng, k):
    n = rng.randint(2, 31)
    v = n * n
    q = f"What is the square root of {v}?"
    sol = [f"{n} × {n} = {v}",
           f"The square root of {v} is the number which, squared, gives {v}."]

    return q, sol, str(n)


def fam_exponent_chain(rng, k):
    a, b = rng.randint(2, 9), rng.randint(2, 3)
    c = rng.randint(2, 50)
    op = rng.choice("+-")
    v1 = a ** b
    final = v1 + c if op == "+" else v1 - c
    q = f"Evaluate {a}^{b} {'+' if op == '+' else '-'} {c}."
    sol = [f"{a}^{b} = {v1}", f"{v1} {op} {c} = {fm(final)}"]
    return q, sol, fm(final)


def fam_time_rate2(rng, k):
    w1, w2 = rng.randint(2, 12), rng.randint(2, 12)
    rate = rng.randint(3, 15)
    v = (w1 + w2) * rate
    q = (f"A worker earns ${rate} per hour and works {w1} hours on Monday "
         f"and {w2} hours on Tuesday. What are the total earnings in dollars?")
    sol = [f"Total hours = {w1} + {w2} = {w1 + w2}",
           f"Earnings = {w1 + w2} × {rate} = {fm(v)}"]
    return q, sol, fm(v)


def fam_two_digit_mult(rng, k):
    a, b = rng.randint(12, 99), rng.randint(11, 99)
    if a == b:
        b += 1
    v = a * b
    tens, units = b - b % 10, b % 10
    q = f"Compute {a} × {b}."
    sol = [f"{a} × {b} = {a} × {tens} + {a} × {units}",
           f"{a} × {tens} = {fm(a * tens)}",
           f"{a} × {units} = {fm(a * units)}",
           f"{fm(a * tens)} + {fm(a * units)} = {fm(v)}"]
    return q, sol, fm(v)


FAMILIES = (
    fam_chain, fam_multichain, fam_percent_of, fam_percent_change,
    fam_frac_add, fam_frac_mul, fam_ratio_share, fam_linear_eq, fam_mean,
    fam_word_discount, fam_rate, fam_inverse_percent, fam_gcd_lcm, fam_perm,
    fam_prob, fam_geometry, fam_decimal, fam_frac_dec, fam_word_multi,
    fam_unit_conv, fam_square_root, fam_exponent_chain, fam_time_rate2,
    fam_two_digit_mult,
)


def generate(total: int = TOTAL) -> list[dict]:
    rng = random.Random(42)
    seen: set[str] = set()
    out: list[dict] = []
    family_tries: dict[str, int] = {f.__name__: 0 for f in FAMILIES}
    MAX_TRIES_PER_FAMILY = 60
    while len(out) < total:
        # family round-robin: the family that has been attempted the least
        f = min(FAMILIES, key=lambda fn: (family_tries[fn.__name__],
                                          FAMILIES.index(fn)))
        if family_tries[f.__name__] >= MAX_TRIES_PER_FAMILY:
            # this family is exhausted; if everything is exhausted, stop
            if all(t >= MAX_TRIES_PER_FAMILY for t in family_tries.values()):
                break
            continue
        family_tries[f.__name__] += 1
        gen = f(rng, len(out))
        if gen is None:
            continue
        q, sol, final = gen
        if not q or not final:
            continue
        fpr = text_fingerprint(q)
        if fpr in seen:
            continue
        # independent re-verification of the rendered steps + boxed final
        bad = verify_lines(sol)
        target = math_response("\n".join(sol), final)
        if bad or "\\boxed{" not in target or not target.endswith(
                f"Final answer: \\boxed{{{final}}}"):
            continue
        if any(t in target for t in ("None", "nan", "inf")):
            continue
        if len(target) > 1600:
            continue
        seen.add(fpr)
        rec = {
            "id": make_id("t32-verified-drills-v1", f"{f.__name__}-{len(out)}", q),
            "source": "t32-verified-drills-v1",
            "license": "MIT",
            "domain": "mathematics",
            "subject": f.__name__.replace("fam_", "drill_"),
            "question": q,
            "answer": final,
            "answer_type": "numeric",
            "difficulty": 2,
            "target_response": target,
            "verification": "step_lines_reverified_and_boxed_checked",
        }
        out.append(rec)
    from collections import Counter
    print("drills:", len(out), dict(Counter(r["subject"] for r in out)))
    return out


def main() -> int:
    recs = generate(TOTAL)
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / "verified_drills.jsonl"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        for r in recs:
            f.write(json.dumps(r, sort_keys=True, ensure_ascii=False) + "\n")
    body = "".join(json.dumps(r, sort_keys=True, ensure_ascii=False) + "\n"
                   for r in recs)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    manifest = {
        "artifact": "T32_VERIFIED_DRILLS",
        "schema_version": "t32-mixture-v1",
        "n": len(recs),
        "families": [f.__name__ for f in FAMILIES],
        "verification": ("forward-computed chains; every rendered arithmetic "
                         "equality re-verified by an independent evaluator "
                         "(split-on-=, consecutive numeric segments must "
                         "agree); boxed final must equal the computed value; "
                         "fails dropped; target <= 1600 chars"),
        "target_contract": "math_response (Final answer: \\boxed{...})",
        "seed": 42,
        "records": path.as_posix(),
        "sha256": digest,
    }
    (OUT / "verified_drills_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    print("sha", digest[:12])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())